// <auto-generated />
namespace Slug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lms_avatarsfromvk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lms_avatarsfromvk));
        
        string IMigrationMetadata.Id
        {
            get { return "201910171315587_lms_avatars from vk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
