// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class keys_not_DB_gen4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keys_not_DB_gen4));
        
        string IMigrationMetadata.Id
        {
            get { return "201905141531075_keys_not_DB_gen4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
