// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pubID_in_Album_label : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pubID_in_Album_label));
        
        string IMigrationMetadata.Id
        {
            get { return "201905171145383_pubID_in_Album_label"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
