// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class phototbo_heightwidth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phototbo_heightwidth));
        
        string IMigrationMetadata.Id
        {
            get { return "201907250752124_photo.tbo_height+width"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
