// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class imgtbo_add_publicID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imgtbo_add_publicID));
        
        string IMigrationMetadata.Id
        {
            get { return "201905170816507_img.tbo_add_publicID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
