// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ip_address_add_UserConnections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ip_address_add_UserConnections));
        
        string IMigrationMetadata.Id
        {
            get { return "201906051126483_ip_address_add_UserConnections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
