// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FriendsRelations_Accepted_rename_to_IsAccepted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FriendsRelations_Accepted_rename_to_IsAccepted));
        
        string IMigrationMetadata.Id
        {
            get { return "201904251155533_FriendsRelations_Accepted_rename_to_IsAccepted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
