// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class album_w_h : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(album_w_h));
        
        string IMigrationMetadata.Id
        {
            get { return "201908051348571_album_w_h"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
