// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Friendship_tbo_enum_ststus_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Friendship_tbo_enum_ststus_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201904260813548_Friendship_tbo_enum_ststus_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
