// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class guid_for_entrys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guid_for_entrys));
        
        string IMigrationMetadata.Id
        {
            get { return "201905101715527_guid_for_entrys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
