// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class guid_secretmsg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guid_secretmsg));
        
        string IMigrationMetadata.Id
        {
            get { return "201908120920555_guid_secretmsg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
