// <auto-generated />
namespace Sluuug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EventComment_non_requered : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventComment_non_requered));
        
        string IMigrationMetadata.Id
        {
            get { return "201905121428186_EventComment_non_requered"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
