// <auto-generated />
namespace Slug.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UsersRelations_as_User2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersRelations_as_User2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002172054182_UsersRelations_as_User2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
